### ISSUE TITLE
Add support for Python 3.6+

### ISSUE THREAD

**Issue by andreyfedoseev** [codacy/codacy-pylint#38]
Python 3.6 (released 2 years ago) introduced new syntax for string formatting (f-strings), see https://www.python.org/dev/peps/pep-0498/ for details.

`codacity-pylint` uses Python 3.5 and reports f-strings as syntax errors.

**Comment by rtfpessoa** [comment]
Fixed in  https://github.com/codacy/codacy-pylint/pull/39 should be available on Monday/Tuesday.
