### ISSUE TITLE
Question. f-string Syntax Error

### ISSUE THREAD

**Issue by moreal** [codacy/codacy-pylint#41]
I have some problems about codacy syntax check.

But I found some issue and pr #38 

But this problem have been occured until now. I want to know the reason this occured

**Comment by rtfpessoa** [comment]
@moreal Codacy supported Python 3 without locking on a specific python version.
In last release we had to fix the build, and Python 3.6 was reverted to 3.4 leading to problems with recent features (since we were not aware of this). The new release put 3.6 back again.
