### ISSUE TITLE
[CY-6634] "Django was not configured" error even when not specified in custom configuration

### ISSUE THREAD

**Issue by y-young** [codacy/codacy-pylint#75]
When using a custom pylint configuration file, even though `pylint_django` is not specified in `load-plugins`, codacy will report an issue:

> Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured (django-not-configured (E5110))

It seems the plugin is always loaded [here](https://github.com/codacy/codacy-pylint/blob/master/src/codacy_pylint.py#L264) and ignores custom configuration.

**Comment by y-young** [comment]
Just saw that there's a separate repository for Python3 pylint, the issue still persists [there](https://github.com/codacy/codacy-pylint-python3/blob/master/src/codacy_pylint.py#L230), maybe someone could transfer this issue there.

**Comment by DMarinhoCodacy** [comment]
Hello everyone,
There is another related issue in the most recent version of this tool, so I'm going to close this issue and follow the other one: https://github.com/codacy/codacy-pylint-python3/issues/213
